site_name: EDAMAME Tutorials
site_url: null
repo_url: https://github.com/edamame-course/docs
site_description: null
site_author: null
site_flavicon: null
theme: bootstrap

pages:
- ['index.md', 'Home']
- ['before/intro_to_ec2_instance.md', 'Before We Begin', 'Setting Up An Amazon EC2 Instance']
- ['before/mobaxterm.md', 'Before We Begin', 'MobaXTerm']
- ['13/test.md', 'Wednesday - August 13th, 2014', 'Test']
